# Tree Model: CatBoostClassifier con sentence embeddings y metadatos

En este notebook se entrena un modelo `CatBoostClassifier` utilizando sentence embeddings y variables contextuales.

Los embeddings se generan con un modelo preentrenado MiniLM, que transforma cada afirmación en un vector semántico. Estos vectores se combinan con metadatos del dataset, como el tema, el hablante, el cargo, el estado y la afiliación política.

El ajuste de hiperparámetros se realiza mediante Optuna, optimizando parámetros como `depth`, `learning_rate`, `l2_leaf_reg`, `iterations` y `border_count`. Finalmente, se ajusta el threshold para maximizar F1 macro.

In [2]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from catboost import CatBoostClassifier, Pool

import optuna
import warnings
warnings.filterwarnings("ignore")

c:\Users\silvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
train_prep = pd.read_csv("../data/train_preprocessed.csv")
test_prep = pd.read_csv("../data/test_preprocessed.csv")

print("Train:", train_prep.shape)
print("Test:", test_prep.shape)

display(train_prep.head())
display(test_prep.head())

Train: (8950, 26)
Test: (3836, 25)

,id,label,statement,subject,speaker,speaker_job,state_info,party_affiliation,statement_clean,statement_length,...,speaker_grouped,speaker_grouped_clean,speaker_job_clean,speaker_job_freq,speaker_job_grouped,speaker_job_grouped_clean,state_info_clean,state_info_freq,party_affiliation_clean,party_affiliation_freq
0,81f884c64a7,1,China is in the South China Sea and (building)...,"china,foreign-policy,military",donald-trump,President-Elect,New York,republican,china is in the south china sea and buildinga ...,116,...,donald-trump,donald trump,president elect,247,President-Elect,president elect,new york,579,republican,3947
1,30c2723a188,0,With the resources it takes to execute just ov...,health-care,chris-dodd,U.S. senator,Connecticut,democrat,with the resources it takes to execute just ov...,164,...,chris-dodd,chris dodd,u s senator,236,U.S. senator,u s senator,connecticut,21,democrat,2898
2,6936b216e5d,0,The (Wisconsin) governor has proposed tax give...,"corporations,pundits,taxes,abc-news-week",donna-brazile,Political commentator,"Washington, D.C.",democrat,the wisconsin governor has proposed tax giveaw...,68,...,donna-brazile,donna brazile,political commentator,15,Political commentator,political commentator,washington d c,89,democrat,2898
3,b5cd9195738,1,Says her representation of an ex-boyfriend who...,"candidates-biography,children,ethics,families,...",rebecca-bradley,unknown,unknown,none,says her representation of an exboyfriend who ...,135,...,other,other,unknown,2482,unknown,unknown,unknown,1930,none,1531
4,84f8dac7737,0,At protests in Wisconsin against proposed coll...,"health-care,labor,state-budget",republican-party-wisconsin,unknown,Wisconsin,republican,at protests in wisconsin against proposed coll...,141,...,republican-party-wisconsin,republican party wisconsin,unknown,2482,unknown,unknown,wisconsin,648,republican,3947

,id,statement,subject,speaker,speaker_job,state_info,party_affiliation,statement_clean,statement_length,statement_word_count,...,speaker_grouped,speaker_grouped_clean,speaker_job_clean,speaker_job_freq,speaker_job_grouped,speaker_job_grouped_clean,state_info_clean,state_info_freq,party_affiliation_clean,party_affiliation_freq
0,dc32e5ffa8b,Five members of [the Common Cause Georgia] boa...,"campaign-finance,ethics,government-regulation",kasim-reed,unknown,unknown,democrat,five members of the common cause georgia board...,89,12,...,kasim-reed,kasim reed,unknown,2482.0,unknown,unknown,unknown,1930.0,democrat,2898
1,aa49bb41cab,Theres no negative advertising in my campaign ...,elections,bill-mccollum,unknown,Florida,republican,theres no negative advertising in my campaign ...,53,9,...,bill-mccollum,bill mccollum,unknown,2482.0,unknown,unknown,florida,853.0,republican,3947
2,dddc8d12ac1,Leticia Van de Putte voted to give illegal imm...,"health-care,immigration,public-health",dan-patrick,Lieutenant governor-elect,Texas,republican,leticia van de putte voted to give illegal imm...,141,23,...,dan-patrick,dan patrick,lieutenant governor elect,18.0,Lieutenant governor-elect,lieutenant governor elect,texas,879.0,republican,3947
3,bcfe8f51667,Fiorinas plan would mean slashing Social Secur...,"federal-budget,medicare,social-security",barbara-boxer,U.S. Senator,California,democrat,fiorinas plan would mean slashing social secur...,63,9,...,barbara-boxer,barbara boxer,u s senator,391.0,U.S. Senator,u s senator,california,121.0,democrat,2898
4,eedbbaff5ab,"By the end of his first term, President Obama ...","federal-budget,new-hampshire-2012",mitt-romney,Former governor,Massachusetts,republican,by the end of his first term president obama w...,115,22,...,mitt-romney,mitt romney,former governor,142.0,Former governor,former governor,massachusetts,167.0,republican,3947

In [3]:
text_cols = [
    "statement_clean",
    "subject_clean",
    "speaker_grouped_clean",
    "speaker_job_grouped_clean",
    "state_info_clean",
    "party_affiliation_clean"
]

for col in text_cols:
    train_prep[col] = train_prep[col].fillna("unknown").astype(str)
    test_prep[col] = test_prep[col].fillna("unknown").astype(str)

In [4]:
train_prep["embedding_text"] = (
    train_prep["statement_clean"] + ". " +
    "Subject: " + train_prep["subject_clean"] + ". " +
    "Speaker: " + train_prep["speaker_grouped_clean"] + ". " +
    "Job: " + train_prep["speaker_job_grouped_clean"] + ". " +
    "State: " + train_prep["state_info_clean"] + ". " +
    "Party: " + train_prep["party_affiliation_clean"]
)

test_prep["embedding_text"] = (
    test_prep["statement_clean"] + ". " +
    "Subject: " + test_prep["subject_clean"] + ". " +
    "Speaker: " + test_prep["speaker_grouped_clean"] + ". " +
    "Job: " + test_prep["speaker_job_grouped_clean"] + ". " +
    "State: " + test_prep["state_info_clean"] + ". " +
    "Party: " + test_prep["party_affiliation_clean"]
)

display(train_prep[["embedding_text", "label"]].head())

                                      embedding_text  label
0  china is in the south china sea and buildinga ...      1
1  with the resources it takes to execute just ov...      0
2  the wisconsin governor has proposed tax giveaw...      0
3  says her representation of an exboyfriend who ...      1
4  at protests in wisconsin against proposed coll...      0

In [5]:
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2726.38it/s]

In [6]:
train_embeddings = embedding_model.encode(
    train_prep["embedding_text"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

test_embeddings = embedding_model.encode(
    test_prep["embedding_text"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Train embeddings:", train_embeddings.shape)
print("Test embeddings:", test_embeddings.shape)

Batches: 100%|██████████| 140/140 [00:35<00:00,  3.93it/s]
Batches: 100%|██████████| 60/60 [00:14<00:00,  4.27it/s]

Train embeddings: (8950, 384)
Test embeddings: (3836, 384)

In [7]:
np.save("../data/train_embeddings_minilm.npy", train_embeddings)
np.save("../data/test_embeddings_minilm.npy", test_embeddings)

In [8]:
embedding_cols = [f"emb_{i}" for i in range(train_embeddings.shape[1])]

train_emb_df = pd.DataFrame(train_embeddings, columns=embedding_cols)
test_emb_df = pd.DataFrame(test_embeddings, columns=embedding_cols)

print("train_emb_df:", train_emb_df.shape)
print("test_emb_df:", test_emb_df.shape)

train_emb_df: (8950, 384)
test_emb_df: (3836, 384)

In [9]:
cat_cols = [
    "subject_clean",
    "speaker_grouped_clean",
    "speaker_job_grouped_clean",
    "state_info_clean",
    "party_affiliation_clean"
]

for col in cat_cols:
    train_prep[col] = train_prep[col].fillna("unknown").astype(str)
    test_prep[col] = test_prep[col].fillna("unknown").astype(str)

In [10]:
num_cols = [
    "statement_length",
    "statement_word_count",
    "num_subjects"
]

optional_freq_cols = [
    "speaker_freq",
    "speaker_job_freq",
    "state_info_freq",
    "party_affiliation_freq"
]

existing_freq_cols = [
    col for col in optional_freq_cols
    if col in train_prep.columns and col in test_prep.columns
]

num_cols = num_cols + existing_freq_cols

train_prep[num_cols] = train_prep[num_cols].fillna(0)
test_prep[num_cols] = test_prep[num_cols].fillna(0)

print("Variables numéricas:", num_cols)

Variables numéricas: ['statement_length', 'statement_word_count', 'num_subjects', 'speaker_freq', 'speaker_job_freq', 'state_info_freq', 'party_affiliation_freq']

In [11]:
train_meta = train_prep[cat_cols + num_cols].reset_index(drop=True)
test_meta = test_prep[cat_cols + num_cols].reset_index(drop=True)

X = pd.concat(
    [
        train_emb_df.reset_index(drop=True),
        train_meta.reset_index(drop=True)
    ],
    axis=1
)

X_test = pd.concat(
    [
        test_emb_df.reset_index(drop=True),
        test_meta.reset_index(drop=True)
    ],
    axis=1
)

y = train_prep["label"]

print("X:", X.shape)
print("y:", y.shape)
print("X_test:", X_test.shape)

X: (8950, 396)
y: (8950,)
X_test: (3836, 396)

In [12]:
cat_feature_indices = [X.columns.get_loc(col) for col in cat_cols]

cat_feature_indices

[384, 385, 386, 387, 388]

In [13]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

train_pool = Pool(X_train, y_train, cat_features=cat_feature_indices)
valid_pool = Pool(X_valid, y_valid, cat_features=cat_feature_indices)
test_pool = Pool(X_test, cat_features=cat_feature_indices)

print("Train:", X_train.shape)
print("Valid:", X_valid.shape)

Train: (7160, 396)
Valid: (1790, 396)

In [14]:
def find_best_threshold_macro(y_true, y_proba):
    thresholds = np.arange(0.40, 0.80, 0.005)
    
    results = []
    
    for threshold in thresholds:
        y_pred = (y_proba >= threshold).astype(int)
        
        results.append({
            "threshold": threshold,
            "accuracy": accuracy_score(y_true, y_pred),
            "f1_macro": f1_score(y_true, y_pred, average="macro"),
            "f1_class_1": f1_score(y_true, y_pred)
        })
    
    results_df = pd.DataFrame(results)
    best_row = results_df.sort_values("f1_macro", ascending=False).iloc[0]
    
    return best_row["threshold"], best_row["f1_macro"], results_df

In [15]:
def objective(trial):
    params = {
        "loss_function": "Logloss",
        "eval_metric": "Logloss",
        "random_seed": 42,
        "verbose": False,
        "allow_writing_files": False,
        
        "iterations": trial.suggest_int("iterations", 500, 2500),
        "depth": trial.suggest_int("depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.005, 0.2, log=True),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 0.01, 100.0, log=True),
        "border_count": trial.suggest_int("border_count", 32, 255)
    }
    
    model = CatBoostClassifier(**params)
    
    model.fit(
        train_pool,
        eval_set=valid_pool,
        early_stopping_rounds=100,
        verbose=False
    )
    
    valid_proba = model.predict_proba(valid_pool)[:, 1]
    
    best_threshold, best_f1_macro, _ = find_best_threshold_macro(
        y_valid,
        valid_proba
    )
    
    trial.set_user_attr("best_threshold", best_threshold)
    
    return best_f1_macro

In [16]:
study = optuna.create_study(direction="maximize")

study.optimize(
    objective,
    n_trials=30,
    show_progress_bar=True
)

[I 2026-05-19 11:34:56,334] A new study created in memory with name: no-name-7ac7df6c-6a35-48a4-b141-fbdf6e41a268
Best trial: 0. Best value: 0.629999:   3%|▎         | 1/30 [00:09<04:38,  9.62s/it]

[I 2026-05-19 11:35:05,951] Trial 0 finished with value: 0.6299992244426389 and parameters: {'iterations': 1167, 'depth': 4, 'learning_rate': 0.1100511136177257, 'l2_leaf_reg': 2.790154057769186, 'border_count': 51}. Best is trial 0 with value: 0.6299992244426389.

Best trial: 0. Best value: 0.629999:   7%|▋         | 2/30 [00:25<06:08, 13.16s/it]

[I 2026-05-19 11:35:21,585] Trial 1 finished with value: 0.5723960552142598 and parameters: {'iterations': 2120, 'depth': 9, 'learning_rate': 0.13848674528679447, 'l2_leaf_reg': 0.0683988215505259, 'border_count': 86}. Best is trial 0 with value: 0.6299992244426389.

Best trial: 0. Best value: 0.629999:  10%|█         | 3/30 [05:35<1:06:54, 148.68s/it]

[I 2026-05-19 11:40:31,548] Trial 2 finished with value: 0.6118650022506944 and parameters: {'iterations': 2416, 'depth': 10, 'learning_rate': 0.005460265515685786, 'l2_leaf_reg': 0.1437083042896526, 'border_count': 167}. Best is trial 0 with value: 0.6299992244426389.

Best trial: 0. Best value: 0.629999:  13%|█▎        | 4/30 [05:51<41:42, 96.24s/it]

[I 2026-05-19 11:40:47,382] Trial 3 finished with value: 0.62082486151429 and parameters: {'iterations': 1517, 'depth': 4, 'learning_rate': 0.06346476395324342, 'l2_leaf_reg': 0.05036021158847295, 'border_count': 95}. Best is trial 0 with value: 0.6299992244426389.

Best trial: 0. Best value: 0.629999:  17%|█▋        | 5/30 [07:24<39:44, 95.38s/it]

[I 2026-05-19 11:42:21,254] Trial 4 finished with value: 0.6142558329663107 and parameters: {'iterations': 1479, 'depth': 10, 'learning_rate': 0.036788276592607826, 'l2_leaf_reg': 4.125998193936993, 'border_count': 126}. Best is trial 0 with value: 0.6299992244426389.

Best trial: 5. Best value: 0.634039:  20%|██        | 6/30 [12:01<1:02:50, 157.12s/it]

[I 2026-05-19 11:46:58,212] Trial 5 finished with value: 0.6340388326284546 and parameters: {'iterations': 2320, 'depth': 9, 'learning_rate': 0.005701258413537212, 'l2_leaf_reg': 5.7367869767292134, 'border_count': 49}. Best is trial 5 with value: 0.6340388326284546.

Best trial: 5. Best value: 0.634039:  23%|██▎       | 7/30 [12:12<41:48, 109.08s/it]

[I 2026-05-19 11:47:08,387] Trial 6 finished with value: 0.6054317596566524 and parameters: {'iterations': 2370, 'depth': 6, 'learning_rate': 0.10762378690061834, 'l2_leaf_reg': 0.015404956754554784, 'border_count': 51}. Best is trial 5 with value: 0.6340388326284546.

Best trial: 5. Best value: 0.634039:  27%|██▋       | 8/30 [13:34<36:51, 100.51s/it]

[I 2026-05-19 11:48:30,533] Trial 7 finished with value: 0.6252628596842247 and parameters: {'iterations': 1549, 'depth': 5, 'learning_rate': 0.005886509524308765, 'l2_leaf_reg': 99.40806459195048, 'border_count': 74}. Best is trial 5 with value: 0.6340388326284546.

Best trial: 5. Best value: 0.634039:  30%|███       | 9/30 [16:30<43:27, 124.18s/it]

[I 2026-05-19 11:51:26,764] Trial 8 finished with value: 0.6315086555229468 and parameters: {'iterations': 2205, 'depth': 6, 'learning_rate': 0.005080940427564322, 'l2_leaf_reg': 0.13744550047779877, 'border_count': 228}. Best is trial 5 with value: 0.6340388326284546.

Best trial: 5. Best value: 0.634039:  33%|███▎      | 10/30 [18:21<40:04, 120.23s/it]

[I 2026-05-19 11:53:18,169] Trial 9 finished with value: 0.6247558131999085 and parameters: {'iterations': 1961, 'depth': 5, 'learning_rate': 0.009146481850516332, 'l2_leaf_reg': 0.9827874396110583, 'border_count': 134}. Best is trial 5 with value: 0.6340388326284546.

Best trial: 5. Best value: 0.634039:  37%|███▋      | 11/30 [19:35<33:34, 106.00s/it]

[I 2026-05-19 11:54:31,903] Trial 10 finished with value: 0.625651912161393 and parameters: {'iterations': 541, 'depth': 8, 'learning_rate': 0.015930475061665013, 'l2_leaf_reg': 54.167081374853566, 'border_count': 193}. Best is trial 5 with value: 0.6340388326284546.

Best trial: 5. Best value: 0.634039:  40%|████      | 12/30 [20:51<29:04, 96.94s/it]

[I 2026-05-19 11:55:48,116] Trial 11 finished with value: 0.6209765543329184 and parameters: {'iterations': 1952, 'depth': 7, 'learning_rate': 0.016454288168662238, 'l2_leaf_reg': 0.5038215411279918, 'border_count': 241}. Best is trial 5 with value: 0.6340388326284546.

Best trial: 12. Best value: 0.636312:  43%|████▎     | 13/30 [22:59<30:03, 106.12s/it]

[I 2026-05-19 11:57:55,340] Trial 12 finished with value: 0.6363124151648896 and parameters: {'iterations': 2471, 'depth': 7, 'learning_rate': 0.011872985870402789, 'l2_leaf_reg': 6.807277503622012, 'border_count': 239}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  47%|████▋     | 14/30 [25:15<30:42, 115.19s/it]

[I 2026-05-19 12:00:11,493] Trial 13 finished with value: 0.6339741847826087 and parameters: {'iterations': 2489, 'depth': 8, 'learning_rate': 0.013195064574529443, 'l2_leaf_reg': 9.898823142272303, 'border_count': 196}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  50%|█████     | 15/30 [26:24<25:21, 101.43s/it]

[I 2026-05-19 12:01:21,050] Trial 14 finished with value: 0.6183026194698211 and parameters: {'iterations': 1806, 'depth': 8, 'learning_rate': 0.028721226023303296, 'l2_leaf_reg': 17.643983438485577, 'border_count': 255}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  53%|█████▎    | 16/30 [28:19<24:37, 105.55s/it]

[I 2026-05-19 12:03:16,158] Trial 15 finished with value: 0.6286305792933764 and parameters: {'iterations': 949, 'depth': 9, 'learning_rate': 0.009193950646656818, 'l2_leaf_reg': 18.503210708749815, 'border_count': 32}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  57%|█████▋    | 17/30 [31:05<26:47, 123.63s/it]

[I 2026-05-19 12:06:01,834] Trial 16 finished with value: 0.6351631151375952 and parameters: {'iterations': 2212, 'depth': 7, 'learning_rate': 0.009406390824932295, 'l2_leaf_reg': 4.610276831342308, 'border_count': 170}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  60%|██████    | 18/30 [32:05<20:53, 104.45s/it]

[I 2026-05-19 12:07:01,623] Trial 17 finished with value: 0.6315086555229468 and parameters: {'iterations': 1825, 'depth': 7, 'learning_rate': 0.0257679552547101, 'l2_leaf_reg': 1.8537760971359944, 'border_count': 206}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  63%|██████▎   | 19/30 [33:08<16:54, 92.21s/it]

[I 2026-05-19 12:08:05,314] Trial 18 finished with value: 0.6257553562394382 and parameters: {'iterations': 2081, 'depth': 3, 'learning_rate': 0.009723993582719026, 'l2_leaf_reg': 0.5226856394041249, 'border_count': 165}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  67%|██████▋   | 20/30 [33:57<13:11, 79.18s/it]

[I 2026-05-19 12:08:54,145] Trial 19 finished with value: 0.6294638129073876 and parameters: {'iterations': 1674, 'depth': 7, 'learning_rate': 0.04437353421187264, 'l2_leaf_reg': 28.165914419795545, 'border_count': 163}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  70%|███████   | 21/30 [34:53<10:47, 72.00s/it]

[I 2026-05-19 12:09:49,389] Trial 20 finished with value: 0.6299038874393104 and parameters: {'iterations': 1150, 'depth': 6, 'learning_rate': 0.022127096772270403, 'l2_leaf_reg': 8.018948709874385, 'border_count': 225}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  73%|███████▎  | 22/30 [38:31<15:26, 115.83s/it]

[I 2026-05-19 12:13:27,442] Trial 21 finished with value: 0.628343282531948 and parameters: {'iterations': 2249, 'depth': 9, 'learning_rate': 0.007491855688693522, 'l2_leaf_reg': 7.368458925367369, 'border_count': 109}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  77%|███████▋  | 23/30 [40:34<13:47, 118.16s/it]

[I 2026-05-19 12:15:31,038] Trial 22 finished with value: 0.6296979262502247 and parameters: {'iterations': 2490, 'depth': 8, 'learning_rate': 0.012388769211316904, 'l2_leaf_reg': 2.1450066879432117, 'border_count': 149}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  80%|████████  | 24/30 [41:51<10:34, 105.71s/it]

[I 2026-05-19 12:16:47,695] Trial 23 finished with value: 0.6234908081275503 and parameters: {'iterations': 2275, 'depth': 7, 'learning_rate': 0.018275518318713352, 'l2_leaf_reg': 4.80523478919097, 'border_count': 181}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  83%|████████▎ | 25/30 [45:21<11:24, 136.98s/it]

[I 2026-05-19 12:20:17,624] Trial 24 finished with value: 0.6278078876504073 and parameters: {'iterations': 2049, 'depth': 9, 'learning_rate': 0.0072285500218182515, 'l2_leaf_reg': 0.9854003193871943, 'border_count': 120}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  87%|████████▋ | 26/30 [47:06<08:30, 127.59s/it]

[I 2026-05-19 12:22:03,317] Trial 25 finished with value: 0.6326890956812217 and parameters: {'iterations': 2292, 'depth': 5, 'learning_rate': 0.01140111481844654, 'l2_leaf_reg': 28.94972580794681, 'border_count': 217}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  90%|█████████ | 27/30 [1:17:09<31:30, 630.21s/it]

[I 2026-05-19 12:52:06,200] Trial 26 finished with value: 0.628624402564345 and parameters: {'iterations': 2174, 'depth': 10, 'learning_rate': 0.007124624602353134, 'l2_leaf_reg': 9.815447386083278, 'border_count': 254}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  93%|█████████▎| 28/30 [1:19:54<16:21, 490.61s/it]

[I 2026-05-19 12:54:51,101] Trial 27 finished with value: 0.6281066537209905 and parameters: {'iterations': 2361, 'depth': 8, 'learning_rate': 0.007224613606644958, 'l2_leaf_reg': 0.5087285727650435, 'border_count': 183}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312:  97%|█████████▋| 29/30 [1:20:29<05:53, 353.85s/it]

[I 2026-05-19 12:55:25,868] Trial 28 finished with value: 0.63097044464969 and parameters: {'iterations': 1875, 'depth': 6, 'learning_rate': 0.020021505033295278, 'l2_leaf_reg': 4.174444737871938, 'border_count': 108}. Best is trial 12 with value: 0.6363124151648896.

Best trial: 12. Best value: 0.636312: 100%|██████████| 30/30 [1:21:42<00:00, 163.40s/it]

[I 2026-05-19 12:56:38,432] Trial 29 finished with value: 0.6289785749875436 and parameters: {'iterations': 1270, 'depth': 7, 'learning_rate': 0.011766637673998813, 'l2_leaf_reg': 1.789010766875852, 'border_count': 67}. Best is trial 12 with value: 0.6363124151648896.

In [17]:
print("Mejor F1 macro:", study.best_value)
print("Mejores parámetros:")
print(study.best_params)

best_threshold_optuna = study.best_trial.user_attrs["best_threshold"]
print("Mejor threshold Optuna:", best_threshold_optuna)

Mejor F1 macro: 0.6363124151648896
Mejores parámetros:
{'iterations': 2471, 'depth': 7, 'learning_rate': 0.011872985870402789, 'l2_leaf_reg': 6.807277503622012, 'border_count': 239}
Mejor threshold Optuna: 0.6150000000000002

In [18]:
best_params = study.best_params.copy()

best_params.update({
    "loss_function": "Logloss",
    "eval_metric": "Logloss",
    "random_seed": 42,
    "verbose": False,
    "allow_writing_files": False
})

best_params

{'iterations': 2471,
 'depth': 7,
 'learning_rate': 0.011872985870402789,
 'l2_leaf_reg': 6.807277503622012,
 'border_count': 239,
 'loss_function': 'Logloss',
 'eval_metric': 'Logloss',
 'random_seed': 42,
 'verbose': False,
 'allow_writing_files': False}

In [19]:
best_model = CatBoostClassifier(**best_params)

best_model.fit(
    train_pool,
    eval_set=valid_pool,
    early_stopping_rounds=100,
    verbose=100
)

valid_proba = best_model.predict_proba(valid_pool)[:, 1]

best_threshold, best_f1_macro, threshold_results = find_best_threshold_macro(
    y_valid,
    valid_proba
)

print("Mejor threshold:", best_threshold)
print("Mejor F1 macro:", best_f1_macro)

display(threshold_results.sort_values("f1_macro", ascending=False).head(15))

0:	learn: 0.6914545	test: 0.6916354	best: 0.6916354 (0)	total: 72.1ms	remaining: 2m 58s
100:	learn: 0.6112785	test: 0.6339557	best: 0.6339557 (100)	total: 7.46s	remaining: 2m 55s
200:	learn: 0.5775896	test: 0.6203648	best: 0.6203648 (200)	total: 14.8s	remaining: 2m 47s
300:	learn: 0.5513359	test: 0.6148988	best: 0.6148945 (299)	total: 22.1s	remaining: 2m 39s
400:	learn: 0.5292589	test: 0.6118080	best: 0.6118080 (400)	total: 30.4s	remaining: 2m 36s
500:	learn: 0.5084655	test: 0.6102994	best: 0.6102082 (498)	total: 38.8s	remaining: 2m 32s
600:	learn: 0.4888575	test: 0.6091829	best: 0.6090798 (593)	total: 47.4s	remaining: 2m 27s
700:	learn: 0.4711847	test: 0.6081000	best: 0.6079847 (689)	total: 55.7s	remaining: 2m 20s
800:	learn: 0.4527993	test: 0.6071116	best: 0.6070742 (799)	total: 1m 3s	remaining: 2m 12s
900:	learn: 0.4332598	test: 0.6069798	best: 0.6067835 (841)	total: 1m 12s	remaining: 2m 6s
1000:	learn: 0.4123120	test: 0.6060323	best: 0.6058680 (985)	total: 1m 22s	remaining: 2m 1s
1100:	learn: 0.3929505	test: 0.6058358	best: 0.6056001 (1065)	total: 1m 31s	remaining: 1m 54s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6056000731
bestIteration = 1065

Shrink model to first 1066 iterations.
Mejor threshold: 0.6150000000000002
Mejor F1 macro: 0.6363124151648896

    threshold  accuracy  f1_macro  f1_class_1
43      0.615  0.667598  0.636312    0.742981
42      0.610  0.669832  0.635825    0.747112
41      0.605  0.669274  0.631367    0.749577
44      0.620  0.659777  0.631357    0.733712
40      0.600  0.669274  0.628347    0.751678
39      0.595  0.671508  0.628026    0.755204
38      0.590  0.673743  0.627280    0.758877
45      0.625  0.652514  0.626783    0.724779
46      0.630  0.648045  0.625191    0.717742
37      0.585  0.673184  0.621943    0.761127
49      0.645  0.636313  0.620893    0.697350
48      0.640  0.638547  0.620824    0.702802
47      0.635  0.641341  0.620445    0.709502
50      0.650  0.627374  0.613849    0.686118
51      0.655  0.624581  0.612973    0.680000

In [20]:
valid_pred = (valid_proba >= best_threshold).astype(int)

print("Accuracy:", accuracy_score(y_valid, valid_pred))
print("F1 macro:", f1_score(y_valid, valid_pred, average="macro"))
print("F1 clase 1:", f1_score(y_valid, valid_pred))

print(classification_report(y_valid, valid_pred))
print(confusion_matrix(y_valid, valid_pred))

Accuracy: 0.6675977653631285
F1 macro: 0.6363124151648896
F1 clase 1: 0.7429805615550756
              precision    recall  f1-score   support

           0       0.53      0.53      0.53       631
           1       0.74      0.74      0.74      1159

    accuracy                           0.67      1790
   macro avg       0.64      0.64      0.64      1790
weighted avg       0.67      0.67      0.67      1790

[[335 296]
 [299 860]]

In [21]:
full_pool = Pool(X, y, cat_features=cat_feature_indices)

final_model = CatBoostClassifier(**best_params)

final_model.fit(
    full_pool,
    verbose=100
)

test_proba = final_model.predict_proba(test_pool)[:, 1]

0:	learn: 0.6916140	total: 71.1ms	remaining: 2m 55s
100:	learn: 0.6150230	total: 7.91s	remaining: 3m 5s
200:	learn: 0.5844156	total: 19s	remaining: 3m 34s
300:	learn: 0.5619914	total: 30.4s	remaining: 3m 38s
400:	learn: 0.5425366	total: 40.6s	remaining: 3m 29s
500:	learn: 0.5252932	total: 50.9s	remaining: 3m 20s
600:	learn: 0.5086299	total: 1m	remaining: 3m 8s
700:	learn: 0.4926537	total: 1m 10s	remaining: 2m 57s
800:	learn: 0.4758783	total: 1m 20s	remaining: 2m 47s
900:	learn: 0.4581867	total: 1m 30s	remaining: 2m 38s
1000:	learn: 0.4405344	total: 1m 40s	remaining: 2m 27s
1100:	learn: 0.4231324	total: 1m 50s	remaining: 2m 17s
1200:	learn: 0.4068352	total: 1m 59s	remaining: 2m 6s
1300:	learn: 0.3905999	total: 2m 10s	remaining: 1m 57s
1400:	learn: 0.3756570	total: 2m 20s	remaining: 1m 47s
1500:	learn: 0.3610688	total: 2m 30s	remaining: 1m 37s
1600:	learn: 0.3475496	total: 2m 40s	remaining: 1m 27s
1700:	learn: 0.3349955	total: 2m 50s	remaining: 1m 17s
1800:	learn: 0.3226434	total: 2m 59s	remaining: 1m 6s
1900:	learn: 0.3113966	total: 3m 9s	remaining: 56.8s
2000:	learn: 0.3007130	total: 3m 19s	remaining: 46.8s
2100:	learn: 0.2896709	total: 3m 29s	remaining: 36.8s
2200:	learn: 0.2794277	total: 3m 38s	remaining: 26.8s
2300:	learn: 0.2700177	total: 3m 48s	remaining: 16.9s
2400:	learn: 0.2606371	total: 3m 57s	remaining: 6.93s
2470:	learn: 0.2543591	total: 4m 5s	remaining: 0us

In [22]:
thresholds_to_try = [
    round(float(best_threshold), 3),
    0.55,
    0.58,
    0.60,
    0.61,
    0.62,
    0.635,
    0.65
]

thresholds_to_try = sorted(set(thresholds_to_try))

for threshold in thresholds_to_try:
    test_predictions = (test_proba >= threshold).astype(int)
    
    submission = pd.DataFrame({
        "id": test_prep["id"],
        "label": test_predictions
    })
    
    filename = f"submission_catboost_embeddings_threshold_{str(threshold).replace('.', '')}.csv"
    submission.to_csv(filename, index=False)
    
    print("\n==============================")
    print("Archivo:", filename)
    print("Threshold:", threshold)
    print("Distribución:")
    print(submission["label"].value_counts())

==============================
Archivo: submission_catboost_embeddings_threshold_055.csv
Threshold: 0.55
Distribución:
label
1    3071
0     765
Name: count, dtype: int64

==============================
Archivo: submission_catboost_embeddings_threshold_058.csv
Threshold: 0.58
Distribución:
label
1    2870
0     966
Name: count, dtype: int64

==============================
Archivo: submission_catboost_embeddings_threshold_06.csv
Threshold: 0.6
Distribución:
label
1    2717
0    1119
Name: count, dtype: int64

==============================
Archivo: submission_catboost_embeddings_threshold_061.csv
Threshold: 0.61
Distribución:
label
1    2622
0    1214
Name: count, dtype: int64

==============================
Archivo: submission_catboost_embeddings_threshold_0615.csv
Threshold: 0.615
Distribución:
label
1    2580
0    1256
Name: count, dtype: int64

==============================
Archivo: submission_catboost_embeddings_threshold_062.csv
Threshold: 0.62
Distribución:
label
1    2544
0    1292
Name: count, dtype: int64

==============================
Archivo: submission_catboost_embeddings_threshold_0635.csv
Threshold: 0.635
Distribución:
label
1    2431
0    1405
Name: count, dtype: int64

==============================
Archivo: submission_catboost_embeddings_threshold_065.csv
Threshold: 0.65
Distribución:
label
1    2299
0    1537
Name: count, dtype: int64

# CatBoost: K-Fold Ensemble

In [23]:
N_SPLITS = 5

skf = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=42
)

oof_proba = np.zeros(len(X))
test_proba_folds = np.zeros((len(X_test), N_SPLITS))

fold_scores = []
models = []

for fold, (train_idx, valid_idx) in enumerate(skf.split(X, y)):
    print(f"\n==============================")
    print(f"Fold {fold + 1} / {N_SPLITS}")
    print(f"==============================")
    
    X_tr = X.iloc[train_idx]
    X_val = X.iloc[valid_idx]
    y_tr = y.iloc[train_idx]
    y_val = y.iloc[valid_idx]
    
    train_pool_fold = Pool(X_tr, y_tr, cat_features=cat_feature_indices)
    valid_pool_fold = Pool(X_val, y_val, cat_features=cat_feature_indices)
    test_pool_fold = Pool(X_test, cat_features=cat_feature_indices)
    
    model = CatBoostClassifier(**best_params)
    
    model.fit(
        train_pool_fold,
        eval_set=valid_pool_fold,
        early_stopping_rounds=100,
        verbose=False
    )
    
    val_proba = model.predict_proba(valid_pool_fold)[:, 1]
    test_proba_fold = model.predict_proba(test_pool_fold)[:, 1]
    
    oof_proba[valid_idx] = val_proba
    test_proba_folds[:, fold] = test_proba_fold
    
    val_pred_05 = (val_proba >= 0.5).astype(int)
    
    fold_scores.append({
        "fold": fold + 1,
        "accuracy": accuracy_score(y_val, val_pred_05),
        "f1_macro": f1_score(y_val, val_pred_05, average="macro"),
        "f1_class_1": f1_score(y_val, val_pred_05),
        "best_iteration": model.get_best_iteration()
    })
    
    models.append(model)

fold_scores_df = pd.DataFrame(fold_scores)
display(fold_scores_df)

print("F1 macro medio:", fold_scores_df["f1_macro"].mean())

==============================
Fold 1 / 5
==============================

==============================
Fold 2 / 5
==============================

==============================
Fold 3 / 5
==============================

==============================
Fold 4 / 5
==============================

==============================
Fold 5 / 5
==============================

   fold  accuracy  f1_macro  f1_class_1  best_iteration
0     1  0.662570  0.518135    0.781949            1069
1     2  0.660894  0.506593    0.782515             675
2     3  0.671508  0.542701    0.785401            1384
3     4  0.669832  0.536131    0.785169            1473
4     5  0.670391  0.541901    0.784514            1306

F1 macro medio: 0.529092243721973

In [24]:
thresholds = np.arange(0.55, 0.72, 0.005)

threshold_results_oof = []

for threshold in thresholds:
    oof_pred = (oof_proba >= threshold).astype(int)
    
    threshold_results_oof.append({
        "threshold": threshold,
        "accuracy": accuracy_score(y, oof_pred),
        "f1_macro": f1_score(y, oof_pred, average="macro"),
        "f1_class_1": f1_score(y, oof_pred)
    })

threshold_results_oof = pd.DataFrame(threshold_results_oof)

display(threshold_results_oof.sort_values("f1_macro", ascending=False).head(20))

best_threshold_oof = threshold_results_oof.sort_values("f1_macro", ascending=False).iloc[0]["threshold"]

print("Mejor threshold OOF:", best_threshold_oof)

    threshold  accuracy  f1_macro  f1_class_1
14      0.620  0.653520  0.619420    0.733339
13      0.615  0.655196  0.617905    0.737272
15      0.625  0.648827  0.617721    0.726767
12      0.610  0.657207  0.617242    0.740922
16      0.630  0.644916  0.616254    0.721130
11      0.605  0.658659  0.615680    0.744202
17      0.635  0.641899  0.615455    0.716296
19      0.645  0.635419  0.614327    0.704519
20      0.650  0.632179  0.613650    0.698258
18      0.640  0.637207  0.613536    0.709180
9       0.595  0.663017  0.611977    0.752706
10      0.600  0.659218  0.611869    0.747433
21      0.655  0.626034  0.609921    0.689200
8       0.590  0.663799  0.609892    0.754908
22      0.660  0.623128  0.609449    0.682541
24      0.670  0.615754  0.605989    0.668018
23      0.665  0.617318  0.605845    0.673093
7       0.585  0.664022  0.605426    0.757480
25      0.675  0.613408  0.605232    0.662043
6       0.580  0.662570  0.599317    0.758516

Mejor threshold OOF: 0.6200000000000001

In [25]:
test_proba_ensemble = test_proba_folds.mean(axis=1)

thresholds_to_try = [
    0.625,
    0.63,
    0.635,
    0.64,
    0.645,
    0.65,
    round(float(best_threshold_oof), 3)
]

thresholds_to_try = sorted(set(thresholds_to_try))

for threshold in thresholds_to_try:
    test_predictions = (test_proba_ensemble >= threshold).astype(int)
    
    submission = pd.DataFrame({
        "id": test_prep["id"],
        "label": test_predictions
    })
    
    filename = f"submission_catboost_kfold_threshold_{str(threshold).replace('.', '')}.csv"
    submission.to_csv(filename, index=False)
    
    print("\n==============================")
    print("Archivo:", filename)
    print("Threshold:", threshold)
    print("Distribución:")
    print(submission["label"].value_counts())

==============================
Archivo: submission_catboost_kfold_threshold_062.csv
Threshold: 0.62
Distribución:
label
1    2501
0    1335
Name: count, dtype: int64

==============================
Archivo: submission_catboost_kfold_threshold_0625.csv
Threshold: 0.625
Distribución:
label
1    2440
0    1396
Name: count, dtype: int64

==============================
Archivo: submission_catboost_kfold_threshold_063.csv
Threshold: 0.63
Distribución:
label
1    2377
0    1459
Name: count, dtype: int64

==============================
Archivo: submission_catboost_kfold_threshold_0635.csv
Threshold: 0.635
Distribución:
label
1    2324
0    1512
Name: count, dtype: int64

==============================
Archivo: submission_catboost_kfold_threshold_064.csv
Threshold: 0.64
Distribución:
label
1    2272
0    1564
Name: count, dtype: int64

==============================
Archivo: submission_catboost_kfold_threshold_0645.csv
Threshold: 0.645
Distribución:
label
1    2205
0    1631
Name: count, dtype: int64

==============================
Archivo: submission_catboost_kfold_threshold_065.csv
Threshold: 0.65
Distribución:
label
1    2148
0    1688
Name: count, dtype: int64

# Modelos adicionales: Transformers
Además del modelo CatBoost con embeddings MiniLM, se probaron modelos Transformer entrenados directamente para la clasificación binaria.

En este caso, el modelo recibe un texto enriquecido que combina la afirmación con metadatos contextuales como el tema, el hablante, el cargo, el estado y el partido político.

# DistilBERT

In [28]:
import sys

!{sys.executable} -m pip install transformers datasets accelerate scikit-learn

Requirement already satisfied: transformers in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (5.8.1)
Collecting datasets
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: scikit-learn in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (1.15.0)
Requirement already satisfied: numpy>=1.17 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in c:\users\silvi\appdata\roaming\python\python311\site-packages (from datasets) (3.20.0)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl.metadata (3.0 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from datasets) (0.28.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.7.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py311-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: psutil in c:\users\silvi\appdata\roaming\python\python311\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: torch>=2.0.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from accelerate) (2.12.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.5-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\silvi\appdata\roaming\python\python311\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: setuptools<82 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->accelerate) (65.5.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.2)
Requirement already satisfied: colorama in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from typer->transformers) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\silvi\appdata\roaming\python\python311\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from pandas->datasets) (2025.3)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.5.2-cp311-cp311-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
     ---------------------------------------- 0.0/82.2 kB ? eta -:--:--
     ---------------------------------------- 82.2/82.2 kB ? eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\silvi\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\silvi\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ---------------------------------------- 0.0/529.0 kB ? eta -:--:--
   --------------------------------------- 529.0/529.0 kB 34.6 MB/s eta 0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ---------------------------------------- 0.0/383.7 kB ? eta -:--:--
   ---------------------------------------- 383.7/383.7 kB ? eta 0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
   ---------------------------------------- 0.0/120.0 kB ? eta -:--:--
   ---------------------------------------- 120.0/120.0 kB ? eta 0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
   ---------------------------------------- 0.0/202.5 kB ? eta -:--:--
   ---------------------------------------- 202.5/202.5 kB ? eta 0:00:00
Downloading multiprocess-0.70.19-py311-none-any.whl (144 kB)
   ---------------------------------------- 0.0/144.5 kB ? eta -:--:--
   ---------------------------------------- 144.5/144.5 kB ? eta 0:00:00
Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   --- ------------------------------------ 2.3/27.3 MB 73.3 MB/s eta 0:00:01
   ------- -------------------------------- 5.1/27.3 MB 65.5 MB/s eta 0:00:01
   ----------- ---------------------------- 7.9/27.3 MB 63.2 MB/s eta 0:00:01
   --------------- ------------------------ 10.7/27.3 MB 59.8 MB/s eta 0:00:01
   ------------------- -------------------- 13.6/27.3 MB 59.5 MB/s eta 0:00:01
   ------------------------ --------------- 16.7/27.3 MB 59.5 MB/s eta 0:00:01
   ---------------------------- ----------- 19.2/27.3 MB 59.5 MB/s eta 0:00:01
   -------------------------------- ------- 22.4/27.3 MB 59.5 MB/s eta 0:00:01
   ------------------------------------- -- 25.2/27.3 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------  27.2/27.3 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------- 27.3/27.3 MB 50.4 MB/s eta 0:00:00
Downloading xxhash-3.7.0-cp311-cp311-win_amd64.whl (31 kB)
Downloading aiohttp-3.13.5-cp311-cp311-win_amd64.whl (462 kB)
   ---------------------------------------- 0.0/462.9 kB ? eta -:--:--
   ---------------------------------------- 462.9/462.9 kB ? eta 0:00:00
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
   ---------------------------------------- 0.0/67.5 kB ? eta -:--:--
   ---------------------------------------- 67.5/67.5 kB ? eta 0:00:00
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
   ---------------------------------------- 0.0/44.1 kB ? eta -:--:--
   ---------------------------------------- 44.1/44.1 kB ? eta 0:00:00
Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
   ---------------------------------------- 0.0/46.0 kB ? eta -:--:--
   ---------------------------------------- 46.0/46.0 kB ? eta 0:00:00
Downloading propcache-0.5.2-cp311-cp311-win_amd64.whl (42 kB)
   ---------------------------------------- 0.0/42.1 kB ? eta -:--:--
   ---------------------------------------- 42.1/42.1 kB 2.0 MB/s eta 0:00:00
Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
   ---------------------------------------- 0.0/87.5 kB ? eta -:--:--
   ---------------------------------------- 87.5/87.5 kB ? eta 0:00:00
Installing collected packages: xxhash, pyarrow, propcache, multidict, fsspec, frozenlist, dill, attrs, aiohappyeyeballs, yarl, multiprocess, aiosignal, aiohttp, datasets, accelerate
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2026.4.0
    Uninstalling fsspec-2026.4.0:
      Successfully uninstalled fsspec-2026.4.0
Successfully installed accelerate-1.13.0 aiohappyeyeballs-2.6.1 aiohttp-3.13.5 aiosignal-1.4.0 attrs-26.1.0 datasets-4.8.5 dill-0.4.1 frozenlist-1.8.0 fsspec-2026.2.0 multidict-6.7.1 multiprocess-0.70.19 propcache-0.5.2 pyarrow-24.0.0 xxhash-3.7.0 yarl-1.23.0

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import random
import torch

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)

In [6]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("GPU disponible:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

GPU disponible: False

In [7]:
transformer_text_cols = [
    "statement_clean",
    "subject_clean",
    "speaker_grouped_clean",
    "speaker_job_grouped_clean",
    "state_info_clean",
    "party_affiliation_clean"
]

for col in transformer_text_cols:
    train_prep[col] = train_prep[col].fillna("unknown").astype(str)
    test_prep[col] = test_prep[col].fillna("unknown").astype(str)

train_prep["transformer_text"] = (
    "Statement: " + train_prep["statement_clean"] +
    " Subject: " + train_prep["subject_clean"] +
    " Speaker: " + train_prep["speaker_grouped_clean"] +
    " Job: " + train_prep["speaker_job_grouped_clean"] +
    " State: " + train_prep["state_info_clean"] +
    " Party: " + train_prep["party_affiliation_clean"]
)

test_prep["transformer_text"] = (
    "Statement: " + test_prep["statement_clean"] +
    " Subject: " + test_prep["subject_clean"] +
    " Speaker: " + test_prep["speaker_grouped_clean"] +
    " Job: " + test_prep["speaker_job_grouped_clean"] +
    " State: " + test_prep["state_info_clean"] +
    " Party: " + test_prep["party_affiliation_clean"]
)

display(train_prep[["transformer_text", "label"]].head())

                                    transformer_text  label
0  Statement: china is in the south china sea and...      1
1  Statement: with the resources it takes to exec...      0
2  Statement: the wisconsin governor has proposed...      0
3  Statement: says her representation of an exboy...      1
4  Statement: at protests in wisconsin against pr...      0

In [8]:
def train_transformer_model(MODEL_NAME, num_epochs=2, batch_size=4, max_length=192):
    
    print("=" * 70)
    print("Entrenando modelo:", MODEL_NAME)
    print("=" * 70)
    
    train_df, valid_df = train_test_split(
        train_prep[["transformer_text", "label"]],
        test_size=0.2,
        random_state=SEED,
        stratify=train_prep["label"]
    )
    
    test_df_transformer = test_prep[["id", "transformer_text"]].copy()
    
    train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
    valid_dataset = Dataset.from_pandas(valid_df.reset_index(drop=True))
    test_dataset = Dataset.from_pandas(test_df_transformer.reset_index(drop=True))
    
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    
    def tokenize_function(batch):
        return tokenizer(
            batch["transformer_text"],
            truncation=True,
            max_length=max_length
        )
    
    train_tokenized = train_dataset.map(tokenize_function, batched=True)
    valid_tokenized = valid_dataset.map(tokenize_function, batched=True)
    test_tokenized = test_dataset.map(tokenize_function, batched=True)
    
    train_tokenized = train_tokenized.rename_column("label", "labels")
    valid_tokenized = valid_tokenized.rename_column("label", "labels")
    
    train_tokenized = train_tokenized.remove_columns(["transformer_text"])
    valid_tokenized = valid_tokenized.remove_columns(["transformer_text"])
    test_tokenized = test_tokenized.remove_columns(["transformer_text", "id"])
    
    train_tokenized.set_format("torch")
    valid_tokenized.set_format("torch")
    test_tokenized.set_format("torch")
    
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2
    )
    
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=1)
        
        return {
            "accuracy": accuracy_score(labels, preds),
            "f1_macro": f1_score(labels, preds, average="macro"),
            "f1_class_1": f1_score(labels, preds)
        }
    
    safe_model_name = MODEL_NAME.replace("/", "_")
    
    training_args = TrainingArguments(
        output_dir=f"./transformer_results_{safe_model_name}",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=num_epochs,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="f1_macro",
        greater_is_better=True,
        logging_steps=50,
        save_total_limit=1,
        report_to="none",
        seed=SEED
    )
    
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
    
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_tokenized,
        eval_dataset=valid_tokenized,
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )
    
    trainer.train()
    
    eval_results = trainer.evaluate()
    
    print("\nResultados en validación:")
    print(eval_results)
    
    valid_outputs = trainer.predict(valid_tokenized)
    valid_logits = valid_outputs.predictions
    valid_proba = torch.softmax(torch.tensor(valid_logits), dim=1).numpy()[:, 1]
    
    print("\nResultados con threshold 0.5:")
    
    valid_pred_05 = (valid_proba >= 0.5).astype(int)
    
    print("Accuracy:", accuracy_score(valid_df["label"], valid_pred_05))
    print("F1 macro:", f1_score(valid_df["label"], valid_pred_05, average="macro"))
    print("F1 clase 1:", f1_score(valid_df["label"], valid_pred_05))
    print(classification_report(valid_df["label"], valid_pred_05))
    print(confusion_matrix(valid_df["label"], valid_pred_05))
    
    thresholds = np.arange(0.30, 0.80, 0.005)
    
    threshold_results = []
    
    for threshold in thresholds:
        valid_pred = (valid_proba >= threshold).astype(int)
        
        threshold_results.append({
            "threshold": threshold,
            "accuracy": accuracy_score(valid_df["label"], valid_pred),
            "f1_macro": f1_score(valid_df["label"], valid_pred, average="macro"),
            "f1_class_1": f1_score(valid_df["label"], valid_pred)
        })
    
    threshold_results = pd.DataFrame(threshold_results)
    threshold_results = threshold_results.sort_values("f1_macro", ascending=False)
    
    display(threshold_results.head(15))
    
    best_threshold = threshold_results.iloc[0]["threshold"]
    best_f1_macro = threshold_results.iloc[0]["f1_macro"]
    
    print("\nMejor threshold:", best_threshold)
    print("Mejor F1 macro validación:", best_f1_macro)
    
    valid_pred_best = (valid_proba >= best_threshold).astype(int)
    
    print("\nResultados con mejor threshold:")
    print("Accuracy:", accuracy_score(valid_df["label"], valid_pred_best))
    print("F1 macro:", f1_score(valid_df["label"], valid_pred_best, average="macro"))
    print("F1 clase 1:", f1_score(valid_df["label"], valid_pred_best))
    print(classification_report(valid_df["label"], valid_pred_best))
    print(confusion_matrix(valid_df["label"], valid_pred_best))
    
    test_outputs = trainer.predict(test_tokenized)
    test_logits = test_outputs.predictions
    test_proba = torch.softmax(torch.tensor(test_logits), dim=1).numpy()[:, 1]
    
    thresholds_to_try = [
        round(float(best_threshold), 3),
        0.45,
        0.50,
        0.52,
        0.55,
        0.60,
        0.62,
        0.635,
        0.65
    ]
    
    thresholds_to_try = sorted(set(thresholds_to_try))
    
    for threshold in thresholds_to_try:
        test_predictions = (test_proba >= threshold).astype(int)
        
        submission = pd.DataFrame({
            "id": test_prep["id"],
            "label": test_predictions
        })
        
        filename = f"submission_{safe_model_name}_threshold_{str(threshold).replace('.', '')}.csv"
        submission.to_csv(filename, index=False)
        
        print("\n==============================")
        print("Archivo:", filename)
        print("Threshold:", threshold)
        print("Distribución:")
        print(submission["label"].value_counts())
    
    np.save(f"../data/test_proba_{safe_model_name}.npy", test_proba)
    np.save(f"../data/valid_proba_{safe_model_name}.npy", valid_proba)
    
    results = {
        "model_name": MODEL_NAME,
        "best_threshold": best_threshold,
        "best_f1_macro_valid": best_f1_macro,
        "eval_results": eval_results
    }
    
    return results

In [15]:
distilbert_results = train_transformer_model(
    MODEL_NAME="distilbert-base-uncased",
    num_epochs=2,
    batch_size=4,
    max_length=192
)

distilbert_results

======================================================================
Entrenando modelo: distilbert-base-uncased
======================================================================

Map: 100%|██████████| 7160/7160 [00:00<00:00, 21632.89 examples/s]
Map: 100%|██████████| 1790/1790 [00:00<00:00, 29343.98 examples/s]
Map: 100%|██████████| 3836/3836 [00:00<00:00, 34217.01 examples/s]
Loading weights: 100%|██████████| 100/100 [00:00<00:00, 9518.23it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.34it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.08it/s]

Resultados en validación:
{'eval_loss': 0.6222476363182068, 'eval_accuracy': 0.6726256983240223, 'eval_f1_macro': 0.629291662720229, 'eval_f1_class_1': 0.7560366361365529}

Resultados con threshold 0.5:
Accuracy: 0.6726256983240223
F1 macro: 0.629291662720229
F1 clase 1: 0.7560366361365529
              precision    recall  f1-score   support

           0       0.54      0.47      0.50       631
           1       0.73      0.78      0.76      1159

    accuracy                           0.67      1790
   macro avg       0.64      0.63      0.63      1790
weighted avg       0.66      0.67      0.67      1790

[[296 335]
 [251 908]]

    threshold  accuracy  f1_macro  f1_class_1
48      0.540  0.673743  0.637214    0.752332
50      0.550  0.671508  0.636709    0.749147
47      0.535  0.673743  0.636349    0.752961
49      0.545  0.672067  0.636347    0.750319
51      0.555  0.669832  0.635550    0.747328
46      0.530  0.672626  0.634811    0.752325
54      0.570  0.667598  0.634723    0.744306
52      0.560  0.668156  0.634661    0.745283
55      0.575  0.667039  0.634512    0.743546
45      0.525  0.672067  0.634041    0.752007
71      0.655  0.654749  0.634020    0.721119
53      0.565  0.667039  0.633703    0.744206
56      0.580  0.665363  0.633604    0.741476
69      0.645  0.655307  0.632601    0.723937
57      0.585  0.663687  0.632428    0.739619

Mejor threshold: 0.5400000000000003
Mejor F1 macro validación: 0.637213705753579

Resultados con mejor threshold:
Accuracy: 0.6737430167597765
F1 macro: 0.637213705753579
F1 clase 1: 0.7523324851569126
              precision    recall  f1-score   support

           0       0.54      0.51      0.52       631
           1       0.74      0.77      0.75      1159

    accuracy                           0.67      1790
   macro avg       0.64      0.64      0.64      1790
weighted avg       0.67      0.67      0.67      1790

[[319 312]
 [272 887]]

==============================
Archivo: submission_distilbert-base-uncased_threshold_045.csv
Threshold: 0.45
Distribución:
label
1    2899
0     937
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_05.csv
Threshold: 0.5
Distribución:
label
1    2762
0    1074
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_052.csv
Threshold: 0.52
Distribución:
label
1    2705
0    1131
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_054.csv
Threshold: 0.54
Distribución:
label
1    2658
0    1178
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_055.csv
Threshold: 0.55
Distribución:
label
1    2630
0    1206
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_06.csv
Threshold: 0.6
Distribución:
label
1    2512
0    1324
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_062.csv
Threshold: 0.62
Distribución:
label
1    2435
0    1401
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_0635.csv
Threshold: 0.635
Distribución:
label
1    2383
0    1453
Name: count, dtype: int64

==============================
Archivo: submission_distilbert-base-uncased_threshold_065.csv
Threshold: 0.65
Distribución:
label
1    2343
0    1493
Name: count, dtype: int64

{'model_name': 'distilbert-base-uncased',
 'best_threshold': np.float64(0.5400000000000003),
 'best_f1_macro_valid': np.float64(0.637213705753579),
 'eval_results': {'eval_loss': 0.6222476363182068,
  'eval_accuracy': 0.6726256983240223,
  'eval_f1_macro': 0.629291662720229,
  'eval_f1_class_1': 0.7560366361365529}}

In [14]:
electra_results = train_transformer_model(
    MODEL_NAME="google/electra-small-discriminator",
    num_epochs=2,
    batch_size=4,
    max_length=192
)

electra_results

======================================================================
Entrenando modelo: google/electra-small-discriminator
======================================================================

Map: 100%|██████████| 7160/7160 [00:00<00:00, 19034.05 examples/s]
Map: 100%|██████████| 1790/1790 [00:00<00:00, 18991.23 examples/s]
Map: 100%|██████████| 3836/3836 [00:00<00:00, 16968.38 examples/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 11577.15it/s]
[transformers] ElectraForSequenceClassification LOAD REPORT from: google/electra-small-discriminator
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
classifier.dense.weight                           | MISSING    |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.out_proj.weight                        | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  8.25it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  9.40it/s]

Resultados en validación:
{'eval_loss': 0.6279868483543396, 'eval_accuracy': 0.6631284916201118, 'eval_f1_macro': 0.593913270195137, 'eval_f1_class_1': 0.7615658362989324}

Resultados con threshold 0.5:
Accuracy: 0.6631284916201118
F1 macro: 0.593913270195137
F1 clase 1: 0.7615658362989324
              precision    recall  f1-score   support

           0       0.53      0.35      0.43       631
           1       0.70      0.83      0.76      1159

    accuracy                           0.66      1790
   macro avg       0.62      0.59      0.59      1790
weighted avg       0.64      0.66      0.64      1790

[[224 407]
 [196 963]]

    threshold  accuracy  f1_macro  f1_class_1
82      0.710  0.639665  0.613588    0.713969
80      0.700  0.640782  0.613075    0.716615
81      0.705  0.638547  0.611905    0.713590
83      0.715  0.636872  0.611670    0.710597
78      0.690  0.641341  0.611512    0.719160
79      0.695  0.640223  0.611336    0.717296
73      0.665  0.644134  0.610360    0.725076
75      0.675  0.643017  0.610252    0.723257
72      0.660  0.644134  0.610079    0.725313
77      0.685  0.640782  0.609985    0.719581
85      0.725  0.632961  0.609924    0.704719
76      0.680  0.641341  0.609654    0.720870
74      0.670  0.642458  0.609226    0.723183
71      0.655  0.643017  0.608286    0.724925
84      0.720  0.631844  0.607823    0.704881

Mejor threshold: 0.7100000000000004
Mejor F1 macro validación: 0.6135882525206041

Resultados con mejor threshold:
Accuracy: 0.6396648044692738
F1 macro: 0.6135882525206041
F1 clase 1: 0.7139689578713969
              precision    recall  f1-score   support

           0       0.49      0.54      0.51       631
           1       0.73      0.69      0.71      1159

    accuracy                           0.64      1790
   macro avg       0.61      0.62      0.61      1790
weighted avg       0.65      0.64      0.64      1790

[[340 291]
 [354 805]]

==============================
Archivo: submission_google_electra-small-discriminator_threshold_045.csv
Threshold: 0.45
Distribución:
label
1    3119
0     717
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_05.csv
Threshold: 0.5
Distribución:
label
1    2960
0     876
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_052.csv
Threshold: 0.52
Distribución:
label
1    2905
0     931
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_055.csv
Threshold: 0.55
Distribución:
label
1    2831
0    1005
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_06.csv
Threshold: 0.6
Distribución:
label
1    2727
0    1109
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_062.csv
Threshold: 0.62
Distribución:
label
1    2679
0    1157
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_0635.csv
Threshold: 0.635
Distribución:
label
1    2634
0    1202
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_065.csv
Threshold: 0.65
Distribución:
label
1    2600
0    1236
Name: count, dtype: int64

==============================
Archivo: submission_google_electra-small-discriminator_threshold_071.csv
Threshold: 0.71
Distribución:
label
1    2426
0    1410
Name: count, dtype: int64

{'model_name': 'google/electra-small-discriminator',
 'best_threshold': np.float64(0.7100000000000004),
 'best_f1_macro_valid': np.float64(0.6135882525206041),
 'eval_results': {'eval_loss': 0.6279868483543396,
  'eval_accuracy': 0.6631284916201118,
  'eval_f1_macro': 0.593913270195137,
  'eval_f1_class_1': 0.7615658362989324}}